Update lighthouse-ci.yaml

diff --git a/.github/workflows/lighthouse-ci.yaml b/.github/workflows/lighthouse-ci.yaml
--- a/.github/workflows/lighthouse-ci.yaml
+++ b/.github/workflows/lighthouse-ci.yaml
@@ -28,16 +28,15 @@ jobs:
         if: steps.wait-for-build.outputs.conclusion == 'success'
         run: |
           npm install -g @lhci/cli@0.3.x
-          echo "URLs: $URL_1 $URL_2"
-          echo "HOST: $HOST_NAME | SITE_NAME: ${{env.SITE_NAME}}"
-          echo "--collect.url=$URL_2"
-          lhci autorun --config=./lighthouserc.ci.js --collect.url=$URL_1 --collect.url=$URL_2 || echo "LHCI failed!"
+          echo "HOST: $HOST_NAME"
+          echo "--collect.url=${{env.HOST_NAME}}/tabs/tab2"
+          lhci autorun --config=./lighthouserc.ci.js \
+            --collect.url=${{env.HOST_NAME}} \
+            --collect.url=${{env.HOST_NAME}}/tabs/tab2 \
+            || echo "LHCI failed!"
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
-          SITE_NAME: "inspiring-wozniak-54afa7"
-          HOST_NAME: "https://deploy-preview-${{github.event.pull_request.number}}--${{env.SITE_NAME}}.netlify.app"
-          URL_1: ${{env.HOST_NAME}}
-          URL_2: ${{env.HOST_NAME}}/tabs/tab2
+          HOST_NAME: "https://deploy-preview-${{github.event.pull_request.number}}--inspiring-wozniak-54afa7.netlify.app"
 
       - name: Netlify build not successful
         if: steps.wait-for-build.outputs.conclusion != 'success'
